// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsxr-VT15DckJ_2n0WdHPKnck05sWc1Bw',
    appId: '1:380669204877:web:6bb378e1f4abd6131a05c4',
    messagingSenderId: '380669204877',
    projectId: 'recipeapp-73714',
    authDomain: 'recipeapp-73714.firebaseapp.com',
    storageBucket: 'recipeapp-73714.appspot.com',
    measurementId: 'G-YNTJ2C5HZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl_tTeN9PZno2rjTXRjB_WiX9pKEkF3Aw',
    appId: '1:380669204877:android:958fb992cf4c051d1a05c4',
    messagingSenderId: '380669204877',
    projectId: 'recipeapp-73714',
    storageBucket: 'recipeapp-73714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWIYTu7OUQ3A7XBrmvVKLWCeIxNTvMNtk',
    appId: '1:380669204877:ios:7573c4ff1aff07e21a05c4',
    messagingSenderId: '380669204877',
    projectId: 'recipeapp-73714',
    storageBucket: 'recipeapp-73714.appspot.com',
    iosClientId: '380669204877-5rsm1n058bfk5roso24nmacf8dhnr1lm.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWIYTu7OUQ3A7XBrmvVKLWCeIxNTvMNtk',
    appId: '1:380669204877:ios:7573c4ff1aff07e21a05c4',
    messagingSenderId: '380669204877',
    projectId: 'recipeapp-73714',
    storageBucket: 'recipeapp-73714.appspot.com',
    iosClientId: '380669204877-5rsm1n058bfk5roso24nmacf8dhnr1lm.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );
}
